### ISSUE TITLE
Login does not work after update

### ISSUE THREAD

**Issue by wmellema** [ScautingBurgum/auti-kafe#2]
During the last push with regards to the login system, the system cannot find the user anymore. This might be because of these 2 lines in the login check page on lines 14/15:
`  $query = "SELECT email, username, password FROM kafelogin WHERE email = '$email'";
    if($query = mysqli_query($conn, $query)) {`

Plz fix!

**Comment by Hexalic** [comment]
Since the login system implementation you need to create a new account. (By registering)
